name:
  local-aws-secrets-extension

services:
  lambda-environment:
    image: lambda-environment
    ports:
      - 3000:3000
    environment:
      SERVER_PORT: 3000
  local-extension:
    image: local-extension
    depends_on:
      - lambda-environment
    ports:
      - 3001:3001
    environment:
      AWS_PROFILE: ${AWS_PROFILE}
      AWS_LAMBDA_RUNTIME_API: "host.docker.internal:3000"
      AWS_SECRETS_EXTENSION_PREFIX: LOCAL_TESTING
      LOCAL_TESTING_LOG_LEVEL: debug
      LOCAL_TESTING_HTTP_PORT: 3001
    volumes:
      - ~/.aws/:/root/.aws:ro
