FROM node:20

WORKDIR /app

COPY ./yarn.lock ./
COPY ./.yarn ./.yarn
COPY ./.yarnrc.yml ./
COPY ./package.json ./
COPY ./tests/inVitro ./tests/inVitro

RUN corepack enable
RUN yarn install --immutable

EXPOSE 3000

CMD [ "yarn", "tsx", "tests/inVitro/localServer.ts"]
