name: Pull request

on:
  pull_request

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run tests
        run: yarn test
