name: Pull request

on:
  pull_request

env:
  HUSKY: 0

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Run unit tests
        run: yarn test-unit

      - name: Build Docker local-extension image
        run: yarn build-local-extension

      - name: Build Docker lambda-environment image
        run: yarn build-lambda-environment

      - name: Run integration tests
        run: yarn test-integration
